#!/usr/bin/env bash
#
# The language gate: no Cyrillic in tracked files.
#
# This repository is English — code, comments, `utoipa` descriptions,
# documentation, templates, workflows and manifests. A rule without a check
# survives until the first hurried commit, so `.github/workflows/ci.yml` runs
# this script on every pull request and a finding fails the pipeline.
#
# Usage:
#   scripts/check-language.sh          # check the tracked files
#   scripts/check-language.sh --list   # print only the offending file names
#
# A non-zero exit code means Cyrillic was found outside the allowlist.

set -euo pipefail

# Files allowed to hold Cyrillic, each with a reason. The list is per-file and
# stays short: an entry here is a decision, not a way of making CI green.
#
# CHANGELOG.md is generated by scripts/changelog.sh from the commit history, and
# that history was deliberately left in Russian (JWT-114) — the historical
# entries cannot be translated without rewriting every commit. New entries are
# English, like the commits they come from.
readonly ALLOWLIST=(
    CHANGELOG.md
)

# The Cyrillic block (U+0400–U+04FF) as raw UTF-8 bytes: lead bytes D0–D3 plus a
# continuation byte. Deliberately NOT `grep -P '[\x{0400}-\x{04FF}]'` — BSD grep
# on macOS has no `-P` and would exit 2, which a bare `if` reads as "no match".
# The gate would then be green on a repository full of Cyrillic, which is the
# one failure mode it must not have. With LC_ALL=C both BSD and GNU grep compare
# bytes and behave identically.
readonly PATTERN='[\xd0-\xd3][\x80-\xbf]'

die() {
    echo "check-language: $*" >&2
    exit 2
}

# Whether $1 holds Cyrillic. A grep exit code above 1 is a scanner failure, not
# an answer — we stop instead of reporting the file as clean.
has_cyrillic() {
    local file="$1" status=0
    LC_ALL=C grep -qIE "$(printf '%b' "$PATTERN")" "$file" || status=$?
    case "$status" in
        0) return 0 ;;
        1) return 1 ;;
        *) die "grep failed on ${file} (exit ${status})" ;;
    esac
}

main() {
    local list_only=0 file entry allowed offenders=()

    while [ $# -gt 0 ]; do
        case "$1" in
            --list)
                list_only=1
                shift
                ;;
            -h | --help)
                sed -n '3,14p' "$0" | sed 's/^# \{0,1\}//'
                return 0
                ;;
            *)
                echo "unknown argument: $1" >&2
                return 2
                ;;
        esac
    done

    git rev-parse --show-toplevel >/dev/null 2>&1 || die "not a git repository"
    cd "$(git rev-parse --show-toplevel)"

    # Tracked files only: build artifacts and ignored local notes
    # (AGENTS_INTERNAL.md) are none of the gate's business.
    while IFS= read -r file; do
        allowed=0
        for entry in "${ALLOWLIST[@]}"; do
            if [ "$file" = "$entry" ]; then
                allowed=1
                break
            fi
        done
        if [ "$allowed" = 0 ] && has_cyrillic "$file"; then
            offenders+=("$file")
        fi
    done < <(git ls-files)

    if [ ${#offenders[@]} -eq 0 ]; then
        [ "$list_only" = 1 ] || echo "check-language: clean"
        return 0
    fi

    if [ "$list_only" = 1 ]; then
        printf '%s\n' "${offenders[@]}"
        return 1
    fi

    echo "check-language: Cyrillic found in ${#offenders[@]} file(s):" >&2
    for file in "${offenders[@]}"; do
        echo "  ${file}" >&2
        LC_ALL=C grep -nIE "$(printf '%b' "$PATTERN")" "$file" | head -n 3 | sed 's/^/    /' >&2
    done
    echo >&2
    echo 'This repository is English (see AGENTS.md, "Repository language").' >&2
    echo "Translate the text, or add the file to the allowlist in $0 with a reason." >&2
    return 1
}

main "$@"
